// <auto-generated/> From DragoAnt.Roslyn.Shared.Sources. Do not edit: this file lives in the NuGet package cache.
#nullable enable

using System;
using Microsoft.CodeAnalysis;

namespace DragoAnt.Roslyn.Shared;

internal static class DiagnosticHelpers
{
    /// <summary>A diagnostic at <paramref name="location"/>, or at <see cref="Location.None"/> when it is <see langword="null"/>.</summary>
    public static Diagnostic Create(DiagnosticDescriptor descriptor, Location? location, params object?[] messageArgs) =>
        Diagnostic.Create(descriptor, location ?? Location.None, messageArgs);

    /// <summary>
    /// Runs <paramref name="body"/> and turns an exception into a <paramref name="fault"/> diagnostic at
    /// <see cref="Location.None"/> (message arguments: exception type, message), so one bad input does not
    /// stop the component with <c>AD0001</c>. Cancellation is never caught.
    /// </summary>
    public static void Guard(DiagnosticDescriptor fault, Action<Diagnostic> report, Action body)
    {
        if (report is null)
        {
            throw new ArgumentNullException(nameof(report));
        }

        try
        {
            body();
        }
        catch (Exception exception) when (exception is not OperationCanceledException)
        {
            report(Diagnostic.Create(fault, Location.None, exception.GetType().FullName, exception.Message));
        }
    }

    /// <summary>Wraps an analysis callback with <see cref="Guard"/>; <paramref name="reportOf"/> picks the context's report method.</summary>
    public static Action<TContext> Guarded<TContext>(
        DiagnosticDescriptor fault, Func<TContext, Action<Diagnostic>> reportOf, Action<TContext> action) =>
        context => Guard(fault, reportOf(context), () => action(context));
}
