// <auto-generated/> From DragoAnt.Roslyn.Shared.Sources. Do not edit: this file lives in the NuGet package cache.
#nullable enable

using System;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DragoAnt.Roslyn.Shared;

internal static class LocationHelpers
{
    /// <summary>
    /// The location of <paramref name="length"/> characters at <paramref name="offset"/> inside a string literal's value.
    /// Falls back to the whole literal when the source text and the value differ (escapes, verbatim, raw or interpolated
    /// strings) or the span does not fit the value.
    /// </summary>
    public static Location InStringLiteral(LiteralExpressionSyntax literal, int offset, int length)
    {
        var token = literal.Token;
        var plain = token.IsKind(SyntaxKind.StringLiteralToken)
                    && token.Text.Length == token.ValueText.Length + 2
                    && token.Text[0] == '"';
        if (!plain || offset < 0 || length < 0 || offset + length > token.ValueText.Length)
        {
            return literal.GetLocation();
        }

        return Location.Create(literal.SyntaxTree, new TextSpan(token.SpanStart + 1 + offset, length));
    }

    /// <summary>
    /// A location in a non-C# file, such as an <see cref="AdditionalText"/>, with line and column computed from
    /// <paramref name="text"/>. The span is clamped to the text.
    /// </summary>
    public static Location InText(string path, SourceText text, int start, int length)
    {
        if (text is null)
        {
            throw new ArgumentNullException(nameof(text));
        }

        start = Math.Max(0, Math.Min(start, text.Length));
        length = Math.Max(0, Math.Min(length, text.Length - start));
        var span = new TextSpan(start, length);
        return Location.Create(path, span, text.Lines.GetLinePositionSpan(span));
    }

    /// <summary>The location of <paramref name="file"/> at <paramref name="start"/>; <see cref="Location.None"/> when its text cannot be read.</summary>
    public static Location InAdditionalText(AdditionalText file, int start, int length, CancellationToken cancellationToken = default)
    {
        var text = file.GetText(cancellationToken);
        return text is null ? Location.None : InText(file.Path, text, start, length);
    }
}
