// <auto-generated/> From DragoAnt.Roslyn.Shared.Sources. Do not edit: this file lives in the NuGet package cache.
#nullable enable

using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Operations;

namespace DragoAnt.Roslyn.Shared;

internal static class SyntaxHelpers
{
    /// <summary>
    /// The parameter an expression is passed to: a call or constructor argument, or a positional or
    /// <c>name:</c> attribute argument. <see langword="null"/> for anything else, e.g. a <c>Name =</c> property assignment.
    /// </summary>
    public static IParameterSymbol? GetTargetParameter(SemanticModel model, ExpressionSyntax expression)
    {
        if (model is null)
        {
            throw new ArgumentNullException(nameof(model));
        }

        switch (expression.Parent)
        {
            case ArgumentSyntax argument:
                return (model.GetOperation(argument) as IArgumentOperation)?.Parameter;

            case AttributeArgumentSyntax { NameEquals: null } attributeArgument
                when attributeArgument.Parent is AttributeArgumentListSyntax { Parent: AttributeSyntax attribute } list:
                if (model.GetSymbolInfo(attribute).Symbol is not IMethodSymbol constructor)
                {
                    return null;
                }

                if (attributeArgument.NameColon is { } nameColon)
                {
                    var name = nameColon.Name.Identifier.ValueText;
                    return constructor.Parameters.FirstOrDefault(p => p.Name == name);
                }

                var index = list.Arguments.IndexOf(attributeArgument);
                if (index < constructor.Parameters.Length)
                {
                    return constructor.Parameters[index];
                }

                var last = constructor.Parameters.LastOrDefault();
                return last is { IsParams: true } ? last : null;

            default:
                return null;
        }
    }

    /// <summary>The value of a compile-time constant string expression, including concatenations and <c>nameof</c>.</summary>
    public static bool TryGetConstantString(SemanticModel model, ExpressionSyntax expression, out string? value)
    {
        if (model is null)
        {
            throw new ArgumentNullException(nameof(model));
        }

        var constant = model.GetConstantValue(expression);
        if (constant.HasValue && constant.Value is string text)
        {
            value = text;
            return true;
        }

        value = null;
        return false;
    }

    /// <summary>Whether <paramref name="symbol"/> carries an attribute of exactly <paramref name="attributeType"/>.</summary>
    public static bool HasAttribute(ISymbol symbol, INamedTypeSymbol attributeType) =>
        symbol.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeType));

    /// <summary>
    /// Whether <paramref name="symbol"/> carries an attribute whose full metadata name is
    /// <paramref name="attributeMetadataName"/> (<c>Namespace.Outer+Inner</c>, generic arity as <c>`1</c>), so a
    /// component can bind to an attribute without referencing the assembly that declares it.
    /// </summary>
    public static bool HasAttribute(ISymbol symbol, string attributeMetadataName) =>
        symbol.GetAttributes().Any(a => a.AttributeClass is { } type && GetFullMetadataName(type) == attributeMetadataName);

    /// <summary>The name <see cref="Compilation.GetTypeByMetadataName"/> takes for <paramref name="type"/>.</summary>
    public static string GetFullMetadataName(INamedTypeSymbol type)
    {
        var builder = new StringBuilder(type.MetadataName);
        var containing = type.ContainingType;
        while (containing is not null)
        {
            builder.Insert(0, containing.MetadataName + "+");
            containing = containing.ContainingType;
        }

        var ns = type.ContainingNamespace;
        while (ns is { IsGlobalNamespace: false })
        {
            builder.Insert(0, ns.MetadataName + ".");
            ns = ns.ContainingNamespace;
        }

        return builder.ToString();
    }
}
