using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace DragoAnt.Roslyn.Shared.Tests;

/// <summary>
/// The rules every shared file follows, and the proof for its <c>// &lt;auto-generated/&gt;</c> header: the header keeps a
/// consumer's own analyzers off a file the consumer cannot edit, and the explicit <c>#nullable enable</c> undoes the one
/// side effect, the nullable context the compiler switches off in generated code.
/// </summary>
public sealed class SharedFileContractTests
{
    public static TheoryData<string> Files() => new(RepositoryPaths.SharedSourceFiles().Select(Relative));

    [Fact]
    public void ThereAreSharedFilesInEveryPart()
    {
        var files = RepositoryPaths.SharedSourceFiles().Select(Relative).ToList();

        files.Should().Contain(f => f.StartsWith("Common/", StringComparison.Ordinal))
            .And.Contain(f => f.StartsWith("Generators/", StringComparison.Ordinal))
            .And.Contain(f => f.StartsWith("CodeFixes/", StringComparison.Ordinal))
            .And.OnlyContain(f => f.StartsWith("Common/", StringComparison.Ordinal)
                                  || f.StartsWith("Generators/", StringComparison.Ordinal)
                                  || f.StartsWith("CodeFixes/", StringComparison.Ordinal));
    }

    [Theory]
    [MemberData(nameof(Files))]
    public void EveryFile_StartsWithTheDoNotEditHeader_ThenEnablesNullable(string file)
    {
        var lines = File.ReadAllLines(Full(file));

        lines[0].Should().StartWith("// <auto-generated/>")
            .And.Contain("DragoAnt.Roslyn.Shared.Sources")
            .And.Contain("Do not edit");
        lines[1].Should().Be("#nullable enable");
    }

    [Theory]
    [MemberData(nameof(Files))]
    public void EveryTopLevelType_IsInternal_InTheSharedNamespace(string file)
    {
        var root = (CompilationUnitSyntax)Parse(file).GetRoot();
        var types = root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>().Where(t => t.Parent is not TypeDeclarationSyntax).ToList();

        types.Should().NotBeEmpty();
        types.Should().OnlyContain(t => t.Modifiers.Any(SyntaxKind.InternalKeyword));
        root.Members.OfType<BaseNamespaceDeclarationSyntax>().Single().Name.ToString().Should().Be("DragoAnt.Roslyn.Shared");
    }

    [Fact]
    public void TheFilesCompile_InAProjectWithNullableOff_WithoutNullableWarnings()
    {
        var compilation = TestCompilation.Create(RepositoryPaths.SharedSourceFiles().Select(Parse), NullableContextOptions.Disable);

        var diagnostics = compilation.GetDiagnostics();

        diagnostics.Where(d => d.Severity >= DiagnosticSeverity.Warning).Should().BeEmpty();
    }

    [Fact]
    public async Task TheHeader_KeepsAnalyzersThatSkipGeneratedCode_OffEveryFile()
    {
        var control = CSharpSyntaxTree.ParseText("namespace Consumer; internal sealed class Own { }", path: "Own.cs");
        var compilation = TestCompilation.Create(RepositoryPaths.SharedSourceFiles().Select(Parse).Append(control));

        var diagnostics = await compilation.WithAnalyzers([new TypeReporter()])
            .GetAnalyzerDiagnosticsAsync(TestContext.Current.CancellationToken);
        var reported = diagnostics.Select(d => Path.GetFileName(d.Location.SourceTree!.FilePath)).Distinct();

        reported.Should().Equal("Own.cs");
    }

    [Fact]
    public void WithoutNullableEnable_TheHeaderSwitchesNullableOff()
    {
        var compilation = TestCompilation.Create("// <auto-generated/>\nclass C { string? F; }");

        compilation.GetDiagnostics().Should().Contain(d => d.Id == "CS8669");
    }

    [Fact]
    public void WithNullableEnable_TheHeaderKeepsNullableWarnings()
    {
        var compilation = TestCompilation.Create("// <auto-generated/>\n#nullable enable\nclass C { string? F; string G = null; }");

        compilation.GetDiagnostics().Select(d => d.Id).Should().Contain("CS8625").And.NotContain("CS8669");
    }

    private static SyntaxTree Parse(string file) =>
        CSharpSyntaxTree.ParseText(File.ReadAllText(Full(file)), path: file);

    private static string Full(string relative) => Path.Combine(RepositoryPaths.SharedSources, relative);

    private static string Relative(string path) =>
        Path.GetRelativePath(RepositoryPaths.SharedSources, path).Replace('\\', '/');

    [DiagnosticAnalyzer(LanguageNames.CSharp)]
    private sealed class TypeReporter : DiagnosticAnalyzer
    {
        private static readonly DiagnosticDescriptor Rule = new(
            "TST100", "Type seen", "Type '{0}' analyzed", "Tests", DiagnosticSeverity.Warning, isEnabledByDefault: true);

        public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => [Rule];

        public override void Initialize(AnalysisContext context)
        {
            context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
            context.EnableConcurrentExecution();
            context.RegisterSymbolAction(c => c.ReportDiagnostic(Diagnostic.Create(Rule, c.Symbol.Locations[0], c.Symbol.Name)), SymbolKind.NamedType);
        }
    }
}
