// <auto-generated/> From DragoAnt.Roslyn.Shared.Sources. Do not edit: this file lives in the NuGet package cache.
#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;

namespace DragoAnt.Roslyn.Shared;

/// <summary>
/// An immutable array compared by its items, so an incremental generator's pipeline model built from it caches.
/// <see langword="default"/> is the empty array.
/// </summary>
internal readonly struct EquatableArray<T> : IEquatable<EquatableArray<T>>, IReadOnlyList<T>
    where T : IEquatable<T>
{
    private readonly T[]? _items;

    public EquatableArray(T[] items) => _items = items is { Length: > 0 } ? (T[])items.Clone() : null;

    public EquatableArray(ImmutableArray<T> items) => _items = items.IsDefaultOrEmpty ? null : items.ToArray();

    public static EquatableArray<T> Empty => default;

    public int Count => _items?.Length ?? 0;

    public bool IsEmpty => Count == 0;

    public T this[int index] => (_items ?? Array.Empty<T>())[index];

    public static bool operator ==(EquatableArray<T> left, EquatableArray<T> right) => left.Equals(right);

    public static bool operator !=(EquatableArray<T> left, EquatableArray<T> right) => !left.Equals(right);

    public bool Equals(EquatableArray<T> other)
    {
        var a = _items ?? Array.Empty<T>();
        var b = other._items ?? Array.Empty<T>();
        if (a.Length != b.Length)
        {
            return false;
        }

        var comparer = EqualityComparer<T>.Default;
        for (var i = 0; i < a.Length; i++)
        {
            if (!comparer.Equals(a[i], b[i]))
            {
                return false;
            }
        }

        return true;
    }

    public override bool Equals(object? obj) => obj is EquatableArray<T> other && Equals(other);

    public override int GetHashCode()
    {
        var hash = 17;
        var comparer = EqualityComparer<T>.Default;
        foreach (var item in _items ?? Array.Empty<T>())
        {
            hash = unchecked((hash * 31) + (item is null ? 0 : comparer.GetHashCode(item)));
        }

        return hash;
    }

    public ImmutableArray<T> AsImmutableArray() => _items is null ? ImmutableArray<T>.Empty : ImmutableArray.Create(_items);

    public IEnumerator<T> GetEnumerator() => ((IEnumerable<T>)(_items ?? Array.Empty<T>())).GetEnumerator();

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}

internal static class EquatableArray
{
    public static EquatableArray<T> ToEquatableArray<T>(this IEnumerable<T> items)
        where T : IEquatable<T> =>
        new(items.ToArray());

    public static EquatableArray<T> ToEquatableArray<T>(this ImmutableArray<T> items)
        where T : IEquatable<T> =>
        new(items);
}
