// <auto-generated/> From DragoAnt.Roslyn.Shared.Sources. Do not edit: this file lives in the NuGet package cache.
#nullable enable

using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DragoAnt.Roslyn.Shared;

internal static class LiteralRewriter
{
    /// <summary>A copy of <paramref name="document"/> with <paramref name="literal"/> replaced by a string literal holding <paramref name="newValue"/>; its trivia is kept.</summary>
    public static async Task<Document> ReplaceStringLiteralAsync(
        Document document, LiteralExpressionSyntax literal, string newValue, CancellationToken cancellationToken = default)
    {
        var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
        return root is null ? document : document.WithSyntaxRoot(ReplaceStringLiteral(root, literal, newValue));
    }

    /// <summary>A copy of <paramref name="root"/> with <paramref name="literal"/> replaced by a string literal holding <paramref name="newValue"/>; its trivia is kept.</summary>
    public static SyntaxNode ReplaceStringLiteral(SyntaxNode root, LiteralExpressionSyntax literal, string newValue)
    {
        var replacement = SyntaxFactory.LiteralExpression(SyntaxKind.StringLiteralExpression, SyntaxFactory.Literal(newValue))
            .WithTriviaFrom(literal);
        return root.ReplaceNode(literal, replacement);
    }
}
